spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/clinicatech
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    mongodb:
      uri: mongodb://localhost:27017/clinicatech
      database: clinicatech

server:
  port: 8080
